# Generated by Django 5.1.4 on 2025-01-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum_app', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='user_name',
        ),
    ]
