# Generated by Django 5.1.4 on 2025-01-11 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum_app', '0003_rename_email_userinfo_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artysta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rozmiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='eksponat',
            name='czy_jest_w_muzeum',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eksponat',
            name='artysta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muzeum_app.artysta'),
        ),
    ]
