# Generated by Django 5.1.4 on 2025-01-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum_app', '0006_rename_galeria_gallery_remove_wypożyczenie_galeria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
