# Generated by Django 5.1.4 on 2025-01-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum_app', '0008_alter_exhibit_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
