# Generated by Django 5.1.4 on 2025-01-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum_app', '0010_alter_userinfo_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
