# Generated by Django 4.2.18 on 2025-01-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum_app', '0011_alter_userinfo_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_password',
            field=models.CharField(max_length=255),
        ),
    ]
