# Generated by Django 5.1.4 on 2025-01-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum_app', '0013_gallery_description_alter_gallery_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('institution', models.CharField(max_length=200)),
                ('gallery', models.CharField(max_length=200)),
                ('exhibit_title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
            ],
        ),
    ]
