# Generated by Django 5.1.4 on 2025-01-31 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum_app', '0014_loanevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muzeum_app.gallery'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='institution_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='loan_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='loan_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='status',
            field=models.CharField(choices=[('in_storage', 'Zamknięty w magazynie'), ('on_display', 'Wystawiony w galerii'), ('on_loan', 'Wypożyczony')], default='in_storage', max_length=20),
        ),
    ]
