# Generated by Django 5.1.4 on 2025-01-31 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum_app', '0015_exhibit_gallery_exhibit_institution_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='status',
            field=models.CharField(choices=[('magazine', 'Magazyn (konserwacja)'), ('gallery', 'Wystawiony w galerii'), ('loaned', 'Wypożyczony'), ('available', 'Dostępny do wypożyczenia')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muzeum_app.institution'),
        ),
    ]
