# Generated by Django 5.1.4 on 2025-02-01 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum_app', '0017_loanhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanevent',
            name='exhibit_title',
        ),
    ]
