# Generated by Django 5.1.4 on 2025-02-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum_app', '0018_remove_loanevent_exhibit_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
