# Generated by Django 5.1.4 on 2025-02-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum_app', '0020_remove_exhibit_artist_remove_exhibit_gallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='location',
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
