# Generated by Django 5.1.4 on 2025-02-01 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum_app', '0021_remove_gallery_location_alter_artist_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LoanEvent',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='institution_city',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='institution_name',
        ),
        migrations.AddField(
            model_name='eksponat',
            name='cenny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eksponat',
            name='status',
            field=models.CharField(choices=[('magazine', 'Magazyn (konserwacja)'), ('gallery', 'Wystawiony w galerii'), ('loaned', 'Wypożyczony'), ('available', 'Dostępny do wypożyczenia')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='muzeum_app.institution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzeum_app.eksponat'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzeum_app.gallery'),
        ),
    ]
