# Generated by Django 5.1.4 on 2025-02-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum_app', '0022_transfer_delete_loanevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
